apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: phone-book
data:
  MYSQL_DATABASE: "phonebook"
  MYSQL_USER: "phonebook_user"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
