apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phone-book

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mysql-deployment.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
  - ingress.yaml

commonLabels:
  project: phone-book
  managed-by: kustomize