---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: phone-book
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "admin"
  MYSQL_PASSWORD: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: phone-book
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "admin"